"""
frontend/pages/2_Narrative_and_WP514.py
=======================================
Page 2 — AI commentary on the findings, and the WP-514 download.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import streamlit as st

from frontend.statements_client import ApiError, statements_api
from frontend import ui

ui.page_setup("Narrative & WP-514", "📄")
session_id, company = ui.require_session()
ui.sidebar_status()
ui.page_header("Review commentary and workpaper", company)

with st.spinner("Writing commentary…"):
    try:
        report = statements_api.review(session_id)
        narrative = statements_api.narrative(session_id)
    except ApiError as error:
        st.error(str(error))
        st.stop()

ui.verdict_banner(report)

summary = narrative["summary"]
if narrative["ai_enabled"]:
    st.caption(f"Generated by `{narrative['model']}` from figures verified in "
               f"the review. {summary['ai_generated']} of "
               f"{summary['sections']} sections model-written, "
               f"{summary['template_fallback']} engine-written.")
else:
    st.info("Language model unavailable — all commentary below is "
            "engine-written from verified figures. The report is complete "
            "either way.")

if summary["number_check_flagged"]:
    st.warning(f"{summary['number_check_flagged']} section(s) cite a figure "
               f"never supplied to the model. Marked below.")

for section in narrative["sections"]:
    ui.narrative_section(section)

st.divider()
st.markdown("##### Download WP-514")
st.write("The workbook contains the cover and sign-off page, every check "
         "across Sections A–E, and this commentary as Section F.")

if st.button("Generate workbook", type="primary"):
    with st.spinner("Assembling…"):
        try:
            content, filename = statements_api.wp514(session_id)
        except ApiError as error:
            st.error(str(error))
            st.stop()
    st.download_button(
        "⬇ Download " + filename, data=content, file_name=filename,
        mime=("application/vnd.openxmlformats-officedocument"
              ".spreadsheetml.sheet"), type="primary")
    st.success("Ready.")
